baseurl = "https://hexagon6.github.com/museomix"
languageCode = "de"
title = "Die Logik einer anderen Zeit"
[params]
  description = "museomix.ch 2016 - Gruppe 6"
  author = "Nikola Tesla"
  logo = "http://www.museomix.ch/wp-content/uploads/2016/04/mmx-logo-2016.png"
  github = "hexagon6"
  twitter = "museomix"
  cover = "/museomix/img/DieLogikeineranderenZeit.png"

  #logo = "http://www.museomix.ch/wp-content/uploads/2016/04/logo-footer.jpg"